import { test, expect } from '@playwright/test';
import type { Project } from '../../shared/domain.js';
import { baselineText } from '../../src/baseline-text.js';

const read = (page: import('@playwright/test').Page): Promise<Project> => page.evaluate(async () => (await fetch('/api/projects/' + localStorage.getItem('active-project'))).json());
test('multi-item list survives failed relationship review without offering placeholder C/D, then retries', async ({ page }) => {
  const old = await initial(page);
  await page.getByRole('button', { name: '加入新功能', exact: true }).click();
  await page.getByLabel('新功能设想', { exact: true }).fill('巡查＋结算＋抓拍');
  await page.getByRole('button', { name: '保存新功能并开始' }).click();
  await expect(page.getByRole('region', { name: '功能归属建议' }).locator('li')).toHaveCount(3);
  await page.route('**/integration/analyze', route => route.fulfill({ status: 502, json: { error: { code: 'invalid_analysis', message: 'AI 返回的结构不符合审查要求，未应用结果，请重试。' } } }));
  await page.getByRole('button', { name: '确认新增清单，审查新旧关系' }).click();
  await expect(page.getByRole('alert')).toContainText('未应用结果');
  await expect(page.getByRole('heading', { name: '新旧功能确认', exact: true })).toBeVisible();
  await expect(page.getByRole('radio')).toHaveCount(0);
  const failed = await read(page); expect(failed.draft.candidates.map(c => c.id)).toEqual(['P0-1','P0-2','P0-3']);
  expect(failed.baseline).toEqual(old.baseline);
  await page.reload(); await expect(page.getByRole('heading', { name: '新旧功能确认', exact: true })).toBeVisible();
  await expect(page.getByRole('radio')).toHaveCount(0);
  await page.unroute('**/integration/analyze');
  await page.getByRole('button', { name: '重新审查新旧关系' }).click();
  await page.getByRole('radio', { name: 'A · 方案一', exact: false }).check();
  await page.getByRole('button', { name: '查看所选决定' }).click();
  await page.getByRole('button', { name: '确认所选决定并接受解决规则', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'MVP 梳理', exact: true })).toBeVisible();
  await expect(page.locator('.candidate-card')).toHaveCount(3);
  await page.getByRole('button', { name: '进入最终确认' }).click();
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: '确认并生成 Baseline v2' }).click();
  expect((await read(page)).baseline!.p0Items.map(c => c.name)).toEqual(['在场监督','结算','抓拍']);
});
async function initial(page: import('@playwright/test').Page, name = '新增功能浏览器') {
  await page.goto('/');
  await page.evaluate(async name => {
    let p = await (await fetch('/api/projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, productDescription: '监督产品', coreUserGoal: '专注监督', productConcept: '屏幕监督', features: ['在场监督'] }) })).json();
    p = await (await fetch(`/api/projects/${p.id}/analyze`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ revision: p.revision }) })).json();
    p = await (await fetch(`/api/projects/${p.id}/commit`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ revision: p.revision, confirmation: '这就是我希望实现的第一版 MVP 产品逻辑。' }) })).json();
    localStorage.setItem('active-project', p.id);
  }, name);
  await page.reload(); return read(page);
}

test('adds a P0 only after classification confirmation, previews differences and commits an immutable current v2', async ({ page }) => {
  const old = await initial(page);
  await page.getByRole('button', { name: '加入新功能', exact: true }).click();
  await page.getByLabel('新功能设想', { exact: true }).fill('用户可以主动暂停监督。');
  await page.getByRole('button', { name: '保存新功能并开始' }).click();
  await expect(page.getByRole('heading', { name: '加入新功能', exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: '功能归属建议' })).toBeVisible();
  expect((await read(page)).draft.candidates).toHaveLength(1);
  expect((await read(page)).baseline).toEqual(old.baseline);
  await page.reload(); await expect(page.getByRole('heading', { name: '加入新功能', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '确认新增清单，审查新旧关系' }).click();
  await expect(page.getByRole('heading', { name: 'MVP 梳理', exact: true })).toBeVisible();
  await expect(page.locator('.feature-status').filter({ hasText: '已明确' })).toHaveCount(2);
  await page.getByRole('navigation').getByRole('button', { name: '产品基线' }).click();
  await expect(page.getByRole('button', { name: '继续本次新增功能草稿' })).toBeVisible();
  expect((await read(page)).baseline).toEqual(old.baseline);
  await page.getByRole('button', { name: '继续本次新增功能草稿' }).click();
  await page.getByRole('button', { name: '进入最终确认' }).click();
  await expect(page.getByRole('region', { name: '本次基线变更' })).toContainText('新增 P0-2');
  await expect(page.getByRole('button', { name: '确认并生成 Baseline v2' })).toBeDisabled();
  await page.getByRole('checkbox', { name: '这就是我希望更新后的当前产品逻辑。' }).check();
  await page.reload(); await expect(page.getByRole('checkbox')).not.toBeChecked();
  await page.getByRole('checkbox').check(); await page.getByRole('button', { name: '确认并生成 Baseline v2' }).click();
  await expect(page.getByRole('heading', { name: '产品基线', exact: true })).toBeVisible();
  const done = await read(page); expect(done.baseline!.baselineVersion).toBe('v2');
  await page.getByLabel('查看基线版本').selectOption('v1');
  await page.locator('main[aria-busy="false"]').waitFor();
  await expect(page.locator('.baseline-view')).not.toContainText('P0-2');
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async (value: string) => sessionStorage.setItem('copied-baseline', value) } }));
  await page.getByRole('button', { name: /复制给 Agent · Baseline v[0-9]+/ }).click();
  expect(await page.evaluate(() => sessionStorage.getItem('copied-baseline'))).toBe(baselineText(old.name, old.baseline!));
  await page.getByLabel('查看基线版本').selectOption('v2'); await page.locator('main[aria-busy="false"]').waitFor();
  await page.getByRole('button', { name: /复制给 Agent · Baseline v[0-9]+/ }).click();
  expect(await page.evaluate(() => sessionStorage.getItem('copied-baseline'))).toBe(baselineText(done.name, done.baseline!));
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '.cache/addition-current-v2.png', fullPage: true });
});

test('confirms an existing P0 adjustment and discards the draft while preserving the current baseline', async ({ page }) => {
  const old = await initial(page);
  await page.getByRole('button', { name: '加入新功能', exact: true }).click();
  await page.getByLabel('新功能设想', { exact: true }).fill('补充在场监督：暂停期间不检测。');
  await page.getByRole('button', { name: '保存新功能并开始' }).click();
  await page.getByRole('button', { name: '确认新增清单，审查新旧关系' }).click();
  await expect(page.getByRole('heading',{name:'新旧功能确认',exact:true})).toBeVisible();
  expect((await read(page)).draft.candidates).toHaveLength(1);
  await page.reload();await expect(page.getByRole('heading',{name:'新旧功能确认',exact:true})).toBeVisible();
  await page.getByRole('radio',{name:'A · 方案一',exact:false}).check();
  await page.getByRole('button',{name:'查看所选决定'}).click();
  const summary = page.getByRole('region',{name:'决定确认汇总'});
  await expect(summary).toContainText('在场监督 · P0-1 · 规则与边界');
  await expect(summary).toContainText('当前内容监督开始后持续显示摄像头识别的人体存在状态；暂停时不判定违规。');
  await expect(summary).toContainText('接受后的内容用户明确允许暂停监督，暂停时不检测，恢复时重新计时。');
  await page.getByRole('button',{name:'确认所选决定并接受解决规则',exact:true}).click();
  await expect(page.getByRole('heading',{name:'MVP 梳理',exact:true})).toBeVisible();
  await page.getByRole('button', { name: '进入最终确认' }).click();
  await expect(page.getByRole('region', { name: '本次基线变更' })).toContainText('调整 P0-1');
  await page.getByRole('button', { name: '返回 MVP 梳理' }).click();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: '放弃本次新增', exact: true }).click();
  await expect(page.getByRole('heading', { name: '产品基线', exact: true })).toBeVisible();
  expect((await read(page)).baseline).toEqual(old.baseline); expect((await read(page)).addition).toBeNull();
});

test('same-P0 doll patrol exposes old/new conflict and requires an accepted rule before replacing real-time detection', async ({ page }) => {
  const old = await initial(page, '玩偶冲突浏览器');
  await page.getByRole('button', { name: '加入新功能', exact: true }).click();
  const request = '补充在场监督：拿着枪的玩偶随机打开门出现在屏幕上，只有玩偶出现时判定违规，连续10秒无违规时离开。';
  await page.getByLabel('新功能设想', { exact: true }).fill(request);
  await page.getByRole('button', { name: '保存新功能并开始' }).click();
  await page.getByRole('button', { name: '确认新增清单，审查新旧关系' }).click();
  await expect(page.getByRole('heading', { name: '实时监督与玩偶巡查冲突', exact: true })).toBeVisible();
  await expect(page.getByRole('article', { name: '本次新增意图' })).toContainText(request);
  await expect(page.getByRole('button', { name: '进入最终确认' })).toHaveCount(0);
  expect((await read(page)).draft.candidates[0]!.coreRule).toBe(old.draft.candidates[0]!.coreRule);
  await page.getByRole('radio', { name: 'C · 暂不确定', exact: false }).check();
  await page.getByRole('button', { name: '查看所选决定' }).click();
  await page.getByRole('button', { name: '确认所选决定', exact: true }).click();
  await page.reload(); await expect(page.getByRole('button', { name: '进入最终确认' })).toHaveCount(0);
  await page.getByRole('radio', { name: 'D · 自定义', exact: false }).check();
  await page.getByLabel('玩偶没有出现时，是否仍判定违规并提醒？', { exact: true }).fill('只有玩偶出现才判断和提醒，摄像头继续提供画面。');
  await page.getByRole('button', { name: '查看所选决定' }).click();
  await page.getByRole('button', { name: '确认所选决定', exact: true }).click();
  await expect(page.getByRole('heading', { name: '实时监督与玩偶巡查冲突', exact: true })).toBeVisible();
  expect((await read(page)).draft.candidates[0]!.coreRule).toBe(old.draft.candidates[0]!.coreRule);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '.cache/doll-conflict-pending.png', fullPage: true });
  await page.getByRole('radio', { name: 'A · 方案一', exact: false }).check();
  await page.getByRole('button', { name: '查看所选决定' }).click();
  await expect(page.getByRole('region', { name: '决定确认汇总' })).toContainText('将明确接受：巡查时判定');
  await page.getByRole('button', { name: '确认所选决定并接受解决规则', exact: true }).click();
  await page.getByRole('button', { name: '进入最终确认' }).click();
  await expect(page.getByRole('region', { name: '本次基线变更' })).toContainText('只有玩偶出现');
  await page.getByRole('checkbox', { name: '这就是我希望更新后的当前产品逻辑。' }).check();
  await page.getByRole('button', { name: '确认并生成 Baseline v2' }).click();
  const done = await read(page); expect(done.baseline!.p0Items[0]!.coreRule).toContain('只有玩偶出现');
  await page.getByLabel('查看基线版本').selectOption('v1');
  await expect(page.locator('.baseline-view')).toContainText(old.draft.candidates[0]!.coreRule);
});
