import { test, expect } from '@playwright/test';

test('full browser flow with explicit conflict resolution, verification, whole commit and preserved projects', async ({ page }) => {
  const consoleErrors: string[] = [];
  page.on('pageerror', e => consoleErrors.push(e.message));
  await page.goto('/');
  await page.getByRole('button', { name: '调整连接与模型', exact: true }).click();
  await expect(page.getByLabel('审查模型', { exact: true })).toBeVisible();
  await expect(page.getByLabel('思考强度', { exact: true })).toHaveValue('high');
  await page.getByLabel('审查模型', { exact: true }).selectOption('gpt-6.1-sol');
  await page.getByLabel('思考强度', { exact: true }).selectOption('medium');
  await page.reload();
  await expect(page.getByLabel('审查模型', { exact: true })).toHaveValue('gpt-6.1-sol');
  await expect(page.getByLabel('思考强度', { exact: true })).toHaveValue('medium');
  const analysisRequest = page.waitForRequest(request => request.url().endsWith('/analyze') && request.method() === 'POST');
  // A legacy candidate project must remain usable after the homepage changes.
  await page.evaluate(async () => {
    const response = await fetch('/api/projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: '专注监督测试', productDescription: '一个通过摄像头监督自律的工具。', coreUserGoal: '用户在专注工作时监督离席行为并收到反馈。', features: ['摄像头监督', '离席超过 10 秒扣心', '允许离席 60 秒免罚'] }) });
    const p = await response.json(); localStorage.setItem('active-project', p.id);
  });
  await page.reload();
  await expect(page.getByRole('heading', { name: 'MVP 梳理', exact: true })).toBeVisible();
  await expect(page.getByText('P0-3')).toBeVisible();
  await page.getByRole('button', { name: 'AI 整理产品草案' }).click();
  expect((await analysisRequest).postDataJSON().inference).toEqual({ connectionId: 'chatgpt', model: 'gpt-6.1-sol', effort: 'medium' });
  await expect(page.getByRole('heading', { name: 'MVP 梳理', exact: true })).toBeVisible();
  await expect(page.getByText('正常监督下的离席处罚与免罚冲突', { exact: true })).toBeVisible();
  await expect(page.getByText('P0-2 要求扣一颗心。', { exact: true })).toBeVisible();
  await expect(page.getByText('P0-3 要求不受处罚。', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '进入最终确认' })).toBeDisabled();
  const before = await page.evaluate(async () => { const projects = await (await fetch('/api/projects')).json(); return (await (await fetch(`/api/projects/${projects[0].id}`)).json()); });
  expect(before.baseline).toBeNull(); expect(before.draft.candidates.every((c: { confirmedException: string }) => !c.confirmedException)).toBe(true);
  await page.getByRole('radio', { name: 'A · 方案一', exact: false }).check();
  await page.getByRole('button', { name: '查看所选决定' }).click();
  await page.getByRole('button', { name: '确认所选决定并接受解决规则', exact: true }).click();
  await page.locator('main[aria-busy="false"]').waitFor();
  await expect(page.getByRole('heading', { name: 'MVP 梳理', exact: true })).toBeVisible();
  const secondP0 = page.locator('article.card').filter({ has: page.getByRole('heading', { name: '离席超过 10 秒扣心', exact: true }) });
  await secondP0.getByText('查看完整定义', { exact: true }).click();
  await secondP0.getByRole('button', { name: '手动编辑', exact: true }).click();
  await expect(page.getByLabel('P0-2 已确认例外规则', { exact: true })).toBeVisible();
  const acceptedRule = await page.getByLabel('P0-2 已确认例外规则', { exact: true }).inputValue();
  await page.getByLabel('P0-2 已确认例外规则', { exact: true }).fill(`${acceptedRule}\n暂停状态不执行普通离席扣心。`);
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: '保存草稿', exact: true }).click();
  await expect(page.getByRole('button', { name: '进入最终确认' })).toBeDisabled();
  await page.getByRole('button', { name: 'AI 整理产品草案' }).click();
  await expect(page.getByRole('heading', { name: 'MVP 梳理', exact: true })).toBeVisible();
  await expect(page.getByLabel('人工测试步骤')).not.toBeVisible();
  await page.locator('.candidate-card').first().getByText('查看完整验收要求', { exact: true }).click();
  await page.locator('.candidate-card').first().getByRole('button', { name: '手动编辑验收要求', exact: true }).click();
  await expect(page.getByLabel('人工测试步骤')).toBeVisible();
  await page.locator('.candidate-card').nth(1).getByText('查看完整验收要求', { exact: true }).click();
  await page.locator('.candidate-card').nth(1).getByRole('button', { name: '手动编辑验收要求', exact: true }).click();
  await expect(page.getByLabel('Agent 验证步骤').first()).toBeVisible();
  await page.getByRole('button', { name: '进入最终确认' }).click();
  await expect(page.getByRole('heading', { name: '最终确认', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '确认并生成 Baseline v1' })).toBeDisabled();
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: '确认并生成 Baseline v1' }).click();
  await expect(page.getByRole('heading', { name: '产品基线', exact: true })).toBeVisible();
  await expect(page.getByText('当前有效基线：v1。正在查看当前基线：v1。所有已提交快照只读。')).toBeVisible();
  await expect(page.getByText('用户每连续监督 30 分钟获得一次临时离席机会', { exact: false }).first()).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: '产品基线', exact: true })).toBeVisible();
  const state = await page.evaluate(async () => ({ auth: await (await fetch('/api/auth')).json(), storage: { ...localStorage }, cookies: document.cookie }));
  expect(JSON.stringify(state)).not.toMatch(/accessToken|refreshToken|id_token|credentials|baseline_session/);
  await page.getByRole('button', { name: '新建项目' }).click();
  await expect(page.getByRole('heading', { name: '产品设想', exact: true })).toBeVisible();
  await page.getByLabel('描述你想象中的产品 · Product Concept / Experience Premise').fill('我想做一个自律监督工具，有玩偶随机巡查，离席会扣心。');
  await page.getByRole('button', { name: '保存设想并开始' }).click();
  await expect(page.getByRole('heading', { name: '产品设想', exact: true })).toBeVisible();
  await page.locator('main[aria-busy="false"]').waitFor();
  await page.getByLabel('选择本地项目').selectOption(before.id);
  await expect(page.getByRole('heading', { name: '产品基线', exact: true })).toBeVisible();
  expect(consoleErrors).toEqual([]);
});
